version: '3.8'

services:
  streamlit-buyer-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rl_buyer_interface_aisupply
    ports:
      - "8503:8501"
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
